services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: web
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  redis_data:

  mongodb_data:
